apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test2  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx-test
  name: nginx-test
  namespace: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-test
    spec:
      containers:
        - image: localhost:5000/nginxhello:v1
          name: nginx-test
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
