apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\OpenshiftPocDockerCompose\angular-springboot-db-sample\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  template:
    metadata:
      annotations:
        kompose.cmd: C:\OpenshiftPocDockerCompose\angular-springboot-db-sample\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/angular-springboot-db-sample-default: "true"
        io.kompose.service: ui
    spec:
      containers:
        - image: ui
          name: ui
          ports:
            - containerPort: 8080
              hostPort: 4200
              protocol: TCP
      restartPolicy: Always
