apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\OpenshiftPocDockerCompose\angular-springboot-db-sample\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  ports:
    - name: "4200"
      port: 4200
      targetPort: 8080
  selector:
    io.kompose.service: ui
