apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: db
    app.kubernetes.io/part-of: employee-manager
    app.kubernetes.io/version: 0.0.1
  name: db
  namespace: employee-manager
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app.kubernetes.io/name: db
    app.kubernetes.io/part-of: employee-manager
    app.kubernetes.io/version: 0.0.1
  type: ClusterIP