apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/part-of: employee-manager
  name: pgadmin
  namespace: employee-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgadmin
      app.kubernetes.io/version: 0.0.1
      app.kubernetes.io/part-of: employee-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgadmin
        app.kubernetes.io/version: 0.0.1
        app.kubernetes.io/part-of: employee-manager
    spec:
      volumes:
        - name: pgadmin-config
          secret:
            secretName: pgadmin-secrets
            defaultMode: 0644
        - name: pgpassfix-volume
          emptyDir: {}

      initContainers:
        - name: volume-mount-hack
          image: busybox
          command:
            [
              "sh",
              "-c",
              "cp -L /usr/local/pgadmin-config/pgpass /usr/local/pgpass-config/ && chown -R 5050:0 /usr/local/pgpass-config && chmod 0600 /usr/local/pgpass-config/pgpass",
            ]
          volumeMounts:
            - name: pgadmin-config
              mountPath: /usr/local/pgadmin-config
            - name: pgpassfix-volume
              mountPath: /usr/local/pgpass-config
      # securityContext:
      #   runAsUser: 5050
      #   runAsGroup: 5050
      #   fsGroup: 5050
      containers:
        - image: docker.io/dpage/pgadmin4:8.5
          name: pgadmin
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: pgadmin-config
              readOnly: true
              mountPath: "/usr/local/pgadmin-config"
            - name: pgpassfix-volume
              mountPath: /usr/local/pgpass-config
          env:
            - name: PGPASSFILE # This pgpass file which we created from pgadmin-secrets.yaml file
              value: "/usr/local/pgpass-config/pgpass"
            - name: PGADMIN_SERVER_JSON_FILE # This sever.jon file which we created from pgadmin-secrets.yaml file
              value: "/usr/local/pgadmin-config/servers.json"
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secrets # pgadmin-secrets.yaml file
                  key: pgadmin-default-email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secrets # pgadmin-secrets.yaml file
                  key: pgadmin-default-password
      restartPolicy: Always
