apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/part-of: employee-manager
    app.kubernetes.io/version: 0.0.1
  name: pgadmin
  namespace: employee-manager
spec:
  ports:
    - nodePort: 31000
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/part-of: employee-manager
    app.kubernetes.io/version: 0.0.1
  sessionAffinity: None
  type: NodePort
