apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
  namespace: employee-manager
stringData:
  pgadmin-default-email: jay.lee@wintrust.com
  pgadmin-default-password: Friday123

  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "postgres",
          "Group": "postgres_group",
          "Host": "db.employee-manager.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "employeemanager_db",
          "Username": "employeemanager_user",
          "PassFile": "/usr/local/pgpass-config/pgpass",
          "SSLMode": "prefer"
        }
      }
    }
  pgpass: |
    db.employee-manager.svc.cluster.local:5432:employeemanager_db:employeemanager_user:employeemanager_development_password
