apiVersion: v1
kind: Service 
metadata:     
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: employee-manager
    app.kubernetes.io/version: 0.0.1
  name: ui
  namespace: employee-manager
spec:
  ports:
  - nodePort: 32233
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: employee-manager
    app.kubernetes.io/version: 0.0.1
  sessionAffinity: None
  type: NodePort